const WORKS = [
  { id: 1, img: '/portfolio/01.jpg', pos: '50% 25%', title: 'Coruja e Bússola', style: '', tag: 'REALISMO', body: 'Braço', hours: '' },
  { id: 2, img: '/portfolio/02.jpg', pos: '50% 35%', title: 'Caveira Ornamental', style: '', tag: 'PRETO E CINZA', body: 'Antebraço', hours: '' },
  { id: 3, img: '/portfolio/03.jpg', pos: '50% 20%', title: 'Perna Triatlon', style: '', tag: 'COR', body: 'Perna', hours: '' },
  { id: 4, img: '/portfolio/04.jpg', pos: '50% 25%', title: 'Retrato Realista', style: '', tag: 'REALISMO', body: 'Braço', hours: '' },
  { id: 5, img: '/portfolio/05.jpg', pos: '50% 30%', title: 'Motociclista ao Pôr do Sol', style: '', tag: 'COR', body: 'Braço', hours: '' },
  { id: 6, img: '/portfolio/06.jpg', pos: '50% 20%', title: 'Fé e Cavaleiro', style: '', tag: 'REALISMO', body: 'Perna', hours: '' },
  { id: 7, img: '/portfolio/07.jpg', pos: '50% 30%', title: 'Leão Realista', style: '', tag: 'REALISMO', body: 'Ombro', hours: '' },
  { id: 8, img: '/portfolio/08.jpg', pos: '50% 30%', title: 'Adaga Neotradicional', style: '', tag: 'COR', body: 'Braço', hours: '' },
  { id: 9, img: '/portfolio/09.jpg', pos: '50% 35%', title: 'Daruma Japonês', style: '', tag: 'PRETO E CINZA', body: 'Braço', hours: '' },
  { id: 10, img: '/portfolio/10.jpg', pos: '50% 30%', title: 'Sapo Estilo Oriental', style: '', tag: 'PRETO E CINZA', body: 'Braço', hours: '' },
  { id: 11, img: '/portfolio/11.jpg', pos: '50% 30%', title: 'Sapo com Cachimbo', style: '', tag: 'PRETO E CINZA', body: 'Braço', hours: '' },
  { id: 12, img: '/portfolio/12.jpg', pos: '50% 30%', title: 'Tigre Oriental', style: '', tag: 'PRETO E CINZA', body: 'Braço', hours: '' },
  { id: 13, img: '/portfolio/13.jpg', pos: '50% 25%', title: 'Retrato Oriental', style: '', tag: 'REALISMO', body: 'Braço', hours: '' },
  { id: 14, img: '/portfolio/14.jpg', pos: '50% 25%', title: 'Retrato Oriental II', style: '', tag: 'REALISMO', body: 'Braço', hours: '' },
  { id: 15, img: '/portfolio/15.jpg', pos: '50% 30%', title: 'Cruz no Peito', style: '', tag: 'PRETO E CINZA', body: 'Peito', hours: '' },
  { id: 16, img: '/portfolio/16.jpg', pos: '50% 30%', title: 'Cruzes Ornamentais', style: '', tag: 'PRETO E CINZA', body: 'Antebraço', hours: '' },
  { id: 17, img: '/portfolio/17.jpg', pos: '50% 20%', title: 'Herança Italiana', style: '', tag: 'REALISMO', body: 'Antebraço', hours: '' },
  { id: 18, img: '/portfolio/18.jpg', pos: '50% 25%', title: 'Falcão Realista', style: '', tag: 'REALISMO', body: 'Braço', hours: '' },
  { id: 19, img: '/portfolio/19.jpg', pos: '50% 20%', title: 'Mulher e Lobo', style: '', tag: 'PRETO E CINZA', body: 'Antebraço', hours: '' },
  { id: 20, img: '/portfolio/20.jpg', pos: '50% 25%', title: 'Anjo Clássico', style: '', tag: 'REALISMO', body: 'Antebraço', hours: '' },
  { id: 21, img: '/portfolio/21.jpg', pos: '50% 20%', title: 'Cristo e Jiu-Jítsu', style: '', tag: 'REALISMO', body: 'Braço', hours: '' },
  { id: 22, img: '/portfolio/22.jpg', pos: '50% 25%', title: 'Operador Tático', style: '', tag: 'REALISMO', body: 'Antebraço', hours: '' },
  { id: 23, img: '/portfolio/23.jpg', pos: '50% 30%', title: 'Onça Rugindo', style: '', tag: 'REALISMO', body: 'Antebraço', hours: '' },
  { id: 24, img: '/portfolio/24.jpg', pos: '50% 25%', title: 'Flor Abstrata', style: '', tag: 'PRETO E CINZA', body: 'Braço', hours: '' },
  { id: 25, img: '/portfolio/25.jpg', pos: '50% 30%', title: 'Estetoscópio Aquarela', style: '', tag: 'COR', body: 'Braço', hours: '' },
  { id: 26, img: '/portfolio/26.jpg', pos: '50% 25%', title: 'Anjo Guardião', style: '', tag: 'REALISMO', body: 'Antebraço', hours: '' },
  { id: 27, img: '/portfolio/27.jpg', pos: '50% 25%', title: 'Águia e Rosa dos Ventos', style: '', tag: 'REALISMO', body: 'Ombro', hours: '' },
  { id: 28, img: '/portfolio/28.jpg', pos: '50% 25%', title: 'Rosas no Ombro', style: '', tag: 'PRETO E CINZA', body: 'Ombro', hours: '' },
  { id: 29, img: '/portfolio/29.jpg', pos: '50% 30%', title: 'Coração com Espinhos', style: '', tag: 'PRETO E CINZA', body: 'Mão', hours: '' },
  { id: 30, img: '/portfolio/30.jpg', pos: '50% 20%', title: 'Escudo do Flamengo', style: '', tag: 'COR', body: 'Perna', hours: '' },
  { id: 31, img: '/portfolio/31.jpg', pos: '50% 20%', title: 'Busto Clássico', style: '', tag: 'REALISMO', body: 'Braço', hours: '' },
  { id: 32, img: '/portfolio/32.jpg', pos: '50% 25%', title: 'Rosto e Rosa', style: '', tag: 'COR', body: 'Perna', hours: '' },
  { id: 33, img: '/portfolio/33.jpg', pos: '50% 30%', title: 'Crisântemo', style: '', tag: 'PRETO E CINZA', body: 'Antebraço', hours: '' },
  { id: 34, img: '/portfolio/34.jpg', pos: '50% 20%', title: 'Ilusão Geométrica', style: '', tag: 'PRETO E CINZA', body: 'Braço', hours: '' },
  { id: 35, img: '/portfolio/35.jpg', pos: '50% 20%', title: 'Odin e os Corvos', style: '', tag: 'REALISMO', body: 'Braço', hours: '' },
  { id: 36, img: '/portfolio/36.jpg', pos: '50% 30%', title: 'Caveira Hexagonal', style: '', tag: 'PRETO E CINZA', body: 'Perna', hours: '' },
  { id: 37, img: '/portfolio/37.jpg', pos: '50% 20%', title: 'Guerreira Nórdica', style: '', tag: 'REALISMO', body: 'Antebraço', hours: '' },
  { id: 38, img: '/portfolio/38.jpg', pos: '50% 30%', title: 'Coragem', style: '', tag: 'PRETO E CINZA', body: 'Antebraço', hours: '' },
  { id: 39, img: '/portfolio/39.jpg', pos: '50% 20%', title: 'Fortis Fortuna', style: '', tag: 'REALISMO', body: 'Perna', hours: '' },
  { id: 40, img: '/portfolio/40.jpg', pos: '50% 25%', title: 'Busto Fragmentado', style: '', tag: 'REALISMO', body: 'Peito', hours: '' },
];
